Suica買い物アプリ課題完了
shinichiowada/shopping pull request #1
Opened 2021-02-24 12:14 UTC by shinichiowada

・Suica買い物アプリを提出します😊

2021-02-24 13:30 UTC, kazu-taka requested changes
@shinichiowada 
数馬くんと同じようなところを間違っていましたが、一緒に勉強しながら課題やってみました？😊
true、falseのあたりはとても重要なので復習お願いします！

2021-02-24 13:30 UTC, kazu-taka commented on index.php
> +        break;
@shinichiowada 
ここは同じようなコードが繰り返されているので、以下のようにすることが可能です！
```php
    case 1:
    case 2:
    case 3:
        $price = $moneys[$msg];
        echo $price . $charge;
        break;
```
ただし`fgets(STDIN);`で入力された値を取得すると、改行コードまで取得されてしまうので、`改行コードを除去するメソッド(fgets(STDIN);)`とするようにしてください✨
改行コードを除去するメソッドは「php fgets 改行」でググるとすぐにでてきます👍

2021-02-24 13:30 UTC, kazu-taka commented on index.php
> +    exit;
@shinichiowada 
1、2、3以外が入力された場合、switchのdefaultを通過するので、ここの2行をdefaultに入れてあげればOKです！
また、defaultは再度の処理になるので、breakは無くても良いです✨

2021-02-24 13:30 UTC, kazu-taka commented on index.php
> +}
@shinichiowada 
無効な番号ですメッセージをswitch文に移動させるので、1、2、3以外の時はここを通過しません。
ですので、`$flag = true`だけでOKです！
"true"はただの文字列の"true"になるので、"は不要です✨

2021-02-24 13:30 UTC, kazu-taka commented on index.php
> +    }
@shinichiowada 
$priceに残高を保持しているので、$numは使用せずに、$priceから代金を引くように修正お願いします✨
同じような使い方をしている変数が複数あると、バグの原因になるので、シンプルに考えてみてください😊

2021-02-24 13:30 UTC, kazu-taka commented on index.php
> +        $num = ($price - $goods);
@shinichiowada 
ここでの()は不要です✨
(上の式では()使わずに計算できています)

2021-02-24 13:30 UTC, kazu-taka commented on index.php
> +} while ($num >= 0);
@shinichiowada 
フローチャートを見て頂くと分かりますが、ループの判定はフラグを使用するので、$flagがtrueの時はループさせるように修正お願いします！

2021-02-24 13:30 UTC, kazu-taka commented on index.php
> +if ($flag == "false") {
@shinichiowada 
ループの判定処理で$flagを使用することで、$flagがfalse以外時はここを通らないので、上記の判定は不要になります✨

2021-02-25 00:29 UTC, shinichiowada commented on index.php
> +        break;
fgets(STDIN); → trim(fgets(STDIN));に修正しました。
条件式が1,2,3共に同じなのでcase 1: 2: 3:とまとめました。

2021-02-25 00:31 UTC, shinichiowada commented on index.php
> +    exit;
2行をdefault内に入れ、breakを削除しました。

2021-02-25 00:32 UTC, shinichiowada commented on index.php
> +}
if文を削除、ダブルクォーテーションを削除し、$flag = trueだけにしました。

2021-02-25 00:34 UTC, shinichiowada commented on index.php
> +    }
$numを削除、$priceで計算式の記述をシンプルにしました。

2021-02-25 00:35 UTC, shinichiowada commented on index.php
> +        $num = ($price - $goods);
シンプルに修正しました。

2021-02-25 00:38 UTC, shinichiowada commented on index.php
> +        break;
fgets(STDIN); → trim(fgets(STDIN));に修正しました。
条件式がcase 1,2,3同じなので上記のご指導通りにまとめました。

2021-02-25 00:40 UTC, shinichiowada commented on index.php
> +    exit;
swich文内のdefaultの中に2行を移動させました。また、breakも削除しました。

2021-02-25 00:42 UTC, shinichiowada commented on index.php
> +}
if文を削除、ダブルクォーテーション削除で$flag = trueだけ残しました。

2021-02-25 00:43 UTC, shinichiowada commented on index.php
> +    }
$priceで展開出来るよう修正しました。

2021-02-25 00:43 UTC, shinichiowada commented on index.php
> +        $num = ($price - $goods);
ここでの計算式をシンプルに修正しました。

2021-02-25 00:45 UTC, shinichiowada commented on index.php
> +if ($flag == "false") {
if文を削除しました。

2021-02-25 01:12 UTC, noopy0415 commented on index.php
> +} while ($price >= 0);
最後の一回も買い物できるので、借金してる状態で終わっちゃいます💦
do ~ whileだと処理後に判定しています。
借金しそうになったら、その前に買い物やめるようにしましょう✨

2021-02-25 04:18 UTC, shinichiowada commented on index.php
> +} while ($price >= 0);
(笑)闇金商法を修正しました。
if文を追加しました😊

2021-02-25 05:00 UTC, noopy0415 commented on index.php
> +} while ($price >= 0);
if文の前でお金は払ってしまってますね😄
お金を払う前に、残高と比較してループから抜けて下さい😆

ちなみにこの方法ならwhile文の条件は要らなくなりますね👍

2021-02-26 07:44 UTC, shinichiowada commented on index.php
> +} while ($price >= 0);
残高が最後まで判るように修正しました。

2021-02-26 08:23 UTC, noopy0415 reviewed
確認お願いします😊

2021-02-26 08:23 UTC, noopy0415 commented on index.php
> +    }
if文で何も処理していないので、この部分は不要です。

2021-02-26 08:23 UTC, noopy0415 commented on index.php
> +echo "チャージ金額を上回るため購入できません。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
残高が0円になっても「チャージ金額を上回るため購入できません。」が表示されます😅
残高が0円の場合は購入できるようにしてください👍
残高が0円になった後は買い物を終了しても良いですが、再度商品の価格入力に戻ってもOKです😊

2021-02-27 01:13 UTC, shinichiowada commented on index.php
> +echo "チャージ金額を上回るため購入できません。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
0円に成っても価格を入力出来るように修正致しました✨

2021-02-27 01:30 UTC, kazu-taka requested changes
@shinichiowada 
コメントしたので確認お願いします✨

2021-02-27 01:30 UTC, kazu-taka commented on index.php
> +        $flag = true;
@shinichiowada 
フローチャートを見て頂きたいのですが、1、2、3以外の数字を入力された場合は、メッセージを表示した後は処理を終了しています。
PHPの`exit`の後は、そこでプログラムを終了するので、`$flag = true;`は実行されません✨
ですので、`$flag = true;`はswitch ($msg) { 〜 }`の後に記述します！
<img src="https://github.com/elites-team/2months_course/raw/master/doc/06_php/exercise_org/06_shopping/images/suica.png">

2021-02-27 01:30 UTC, kazu-taka commented on index.php
> +} while ($price >= 0);
@shinichiowada 
こちらも先程のフローチャートを見て頂きたいのですが、「商品の価格を入力して下さい」と表示した後に、`残高 >= 商品の代金`を確認して、true、falseで処理が分かれています。
フローチャートにしてがって、if、elseで処理を分岐するようにお願いします✨
また、残高でループを続行するか判断しているので(`while ($price >= 0)`)、残高ではなく、`$flag`で判断するようにお願いします🙏

2021-02-27 05:30 UTC, kazu-taka requested changes
@shinichiowada
フローチャートと異なる部分が多数あるので、修正お願いします🙏

2021-02-27 05:30 UTC, kazu-taka commented on index.php
> +        $flag = true;
@shinichiowada 
$flagはフローチャートの買い物フラグに該当すると思いますが、買い物フラグの設定はswitch外で且つ、ループの前で実行することになっています✨
defaultでやるべきことはメッセージを表示して、終了するだけになるので、ここでのフラグ設定は不要になります！
![Suica](https://user-images.githubusercontent.com/5278718/109376069-4c7d2780-7905-11eb-8568-bab8ee05ea1b.jpg)

2021-02-27 05:30 UTC, kazu-taka commented on index.php
> +    echo "残高は{$price}円です。" . PHP_EOL;
@shinichiowada 
こちらもフローチャートを確認してみて下さい✨
言葉に表すと以下のような処理になります。

- 1. ループの処理開始
- 2. メッセージの表示(商品の価格を入力して下さい)
- 3. 残高 >= 商品の代金判定
  - trueの時
    -  残高 - 商品の代金を実行
    - メッセージの表示(残高は◯◯円です。)
  - falseの時
    -  残高 - 商品の代金を実行
    - メッセージの表示(残高は◯◯円です。)
- 4. ループの継続判定(買い物フラグ == true)
- 5. ループを抜けたらメッセージを表示(買い物を終了します。)

### 現状

-  残高 >= 商品の代金判定をする前に残高から代金を引いてしまっている
- フラグの初期化がループの中に入ってしまっている
- 残高は◯◯円ですのメッセージがif文の外で実行されている。
- ifがfalseの場合、フラグを更新するだけで良いが、exitしてしまっている。
- ループの継続条件が買い物フラグで判定するべきところ、`$price >= 0`で判定されている。この条件でも正常に動きますが、フローチャートと異なっている
- 買い物を終了しますのメッセージをループ内で出力している

![if](https://user-images.githubusercontent.com/5278718/109376223-7edb5480-7906-11eb-9388-6ba19277d5e8.jpg)

まずは、フローチャートをコードに落とし込むところを意識してみて下さい😊

2021-02-27 05:30 UTC, kazu-taka commented on index.php
> +    echo "残高は{$price}円です。" . PHP_EOL;
@shinichiowada 
余談ですが以下のようにtrueの時に何も処理しないのであれば、条件を変更して、falseの処理を無くすようにして下さい✨
```php
    if ($price >= 0) {
    } else {
        $flag = false;
        echo "チャージ金額を上回るため購入できません。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
        exit;
    }


// このような書き方ができます
    if ($price < 0) {
        $flag = false;
        echo "チャージ金額を上回るため購入できません。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
        exit;
    }
```

2021-02-27 08:31 UTC, kazu-taka requested changes
@shinichiowada 
フローチャート通りに記述されていないので、一度do以降を全て消してから、フローチャート通りに記述して頂いた方が整理できるかもしれません^^;
修正お願いします🙏

2021-02-27 08:31 UTC, kazu-taka commented on index.php
> +        exit;
@shinichiowada 
フローチャートのif文のところを見ると、「残高 >= 商品の代金」となっています。
ですので、`$price = $price - $goods < 0`ではなく`$price >= $goods`で判定して下さい！
条件式もフローチャートの図の内容をそのままコードに置き換えて頂ければOKです！
![if](https://user-images.githubusercontent.com/5278718/109381917-890a4c80-7920-11eb-878c-75665f6ebbd7.jpg)

条件式は以下のようになります✨

```php
if ($price >= $goods) {
    // trueの処理
} else {
    // falseの処理
}
```

上記のtrueとfalseの処理は、前回指摘させて頂いた以下の内容を記述するようにお願いします:bow:

- trueの時
  - 残高 - 商品の代金を実行
  - メッセージの表示(残高は◯◯円です。)
- falseの時
  - 残高 - 商品の代金を実行
  - メッセージの表示(残高は◯◯円です。)

また、現状、do〜whileの中でexitを使用していますが、フローチャートには、exitを表す矢印(処理終了まで伸びる矢印)がないので、今回はexitを使用してはいけません。

2021-02-27 08:31 UTC, kazu-taka commented on index.php
> +} while ($price >= 0);
@shinichiowada 
こちらのも部分もフローチャートに合わせて、loopの判定条件に$flagを使用するようにお願いします:bow:

2021-02-27 13:02 UTC, kazu-taka commented on index.php
> +        $flag == false;
@shinichiowada 
`==`演算子は比較の時に使用するので、ここでfalseは代入されません！
`=`を使用するようにして下さい✨

2021-02-27 13:10 UTC, kazu-taka requested changes
@shinichiowada 
惜しいですが、細かいミスがあったので修正お願いします🙏

2021-02-27 13:10 UTC, kazu-taka commented on index.php
> +echo "買い物を終了します。";
@shinichiowada 
ループの後ろは別の処理になるので、1行空けた方がいいですね✨

2021-02-27 13:10 UTC, kazu-taka commented on index.php
> +        break;
@shinichiowada 
フローチャートのifのelseの処理ですが、矢印がループの外に出ていないので、ここでのbreakは不要です。
多分breakを入れないとうまく処理されなかったのでいれたと思いますが、原因はループの判定が`while ($flag = true)`になっているからです！
`=`は代入という意味ですので、比較にはなっていません✨
フローチャートにも問題がある時はありますが、慌てずフローチャート通りに書いて、それでもいまくいかない時は、さきほどのように`==`や`=`のような細かいミスの場合もあるので、コードを書いたら1文字ずつ確認してみて下さい😊

2021-02-27 13:10 UTC, kazu-taka commented on index.php
> +    // Suicaの残高 >= 商品の価格
@shinichiowada 
上の代入とif は別の処理になるので、ここも1行空けた方がいいと思います✨

2021-02-27 13:10 UTC, kazu-taka commented on index.php
> +$flag = true;
@shinichiowada 
switchとフラグ設定は別の処理になるので、間を1行空けた方がいいと思います✨

2021-02-27 23:51 UTC, kazu-taka commented on index.php
> +        $flag == true;
@shinichiowada 
ここもフローチャートに合わせて欲しいところになります✨
ループに入る前にフラグをtrueにしているので、ここの処理を通過する時は必ずtrueになっているので、trueにする必要はありません😊

2021-02-28 00:24 UTC, kazu-taka commented on index.php
> -        $flag == true;
@shinichiowada 
見落としてましたが、もし$flagにtrueを設定するつもりでしたら、`==`ではなく`=`になります！
また、`while ($flag == true);`は、「$flagがtrueだったら」という判定の意味になるので、$flagにtrueを設定しているというわけではありません✨
そこを理解できているのであれば今回の修正も安心してOK出せます😊

2021-02-28 00:25 UTC, kazu-taka commented
@shinichiowada 
マージしてOKです✨
![LGTM](https://image.lgtmoon.dev/22163)

2021-02-28 03:21 UTC, merged